import './globals.css';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import { Open_Sans } from 'next/font/google';
import Footer from '@/components/footer';

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-manrope' 
});
const openSans = Open_Sans({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-openSans' 
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${openSans.variable} bg-white`}>
        {children}
        <section className="mb-10 mt-[90px]">
          <Footer />
        </section>
      </body>
    </html>
  );
}
